### Lab signup
POST http://localhost:1247/register/lab HTTP/1.1
Content-Type: application/json

{
    "email" : "valid-email",
    "contact": "valid-indian-number",
    "username" : ".......",
    "password" : "......."   // should be alphanumeric(should contain capitals, small letters, numbers, special chars
}

### Lab login
POST http://localhost:1247/login/lab HTTP/1.1
Content-Type: application/json

{
    "username" : "......",
    "password" : "......"
}

### Test
GET http://localhost:1247/lab/ HTTP/1.1

### Logout
DELETE http://localhost:1247/lab/logout HTTP/1.1